In [27]:
!python --version

from math import sqrt
import numpy as np

Python 3.13.9


In [2]:
x = 3
print(x, type(x))

3 <class 'int'>


In [3]:
t, f = True, False
print(type(t))

<class 'bool'>


In [4]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


In [5]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter

hw12 = f'{hello} {world} {12}'  # string formatting with f-string
print(hw12)

hello world 12


In [6]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [7]:
xs = [3, 1, 2]
print(xs, xs[2])
print(xs[-1])

[3, 1, 2] 2
2


In [8]:
x = xs.pop()
print(x, xs)

2 [3, 1]


In [9]:
nums = list(range(5))    # range generates a sequence of integers; list() converts it to a list
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [10]:
animals = ["cat", "dog", "monkey"]
for animal in animals:
    print(animal)

cat
dog
monkey


In [11]:
animals = ["cat", "dog", "monkey"]
for idx, animal in enumerate(animals):
    print(f"#{idx + 1}: {animal}")

#1: cat
#2: dog
#3: monkey


List comprehensions:

In [12]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


In [13]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [14]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [15]:
pets = {"cat": "cute",
     "dog": "furry"}

print(pets["cat"])
print("cat" in pets)

cute
True


In [16]:
pets["goldfish"] = "wet"
print(pets)

{'cat': 'cute', 'dog': 'furry', 'goldfish': 'wet'}


In [17]:
del pets["cat"]
print(pets)

{'dog': 'furry', 'goldfish': 'wet'}


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [18]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [19]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


True
False


In [20]:
animals.add('fish') 
print(len(animals)) 

3


Loops: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [21]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(f'#{idx + 1}: {animal}')

#1: cat
#2: dog
#3: fish


Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [22]:
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. 

Here is a trivial example:

In [23]:
plus_one = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
tuple = (5, 6)  # Create a tuple

print(plus_one)
print(plus_one[tuple])  # (5, 6): 5
print(plus_one[(7, 8)]) 

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
7


Functions

In [24]:
def sign(x):
    if (x > 0):
        return "positive"
    elif (x < 0):
        return "negative"
    else:
        return "zero"
    
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [25]:
def hello(name, loud=False):
    if loud:
        print(f"Hello, {name.upper()}")
    else:
        print(f"Hello, {name}")

hello("Mikey")
hello("John", loud=True)

Hello, Mikey
Hello, JOHN


Classes

In [26]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name    # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print(f"HELLO, {self.name.upper()}")
        else:
            print(f"Hello, {self.name}!")

g = Greeter("Fred")
g.greet()  
g.greet(loud=True)  

Hello, Fred!
HELLO, FRED


Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [33]:
a = np.array([1, 2, 3]) # Create a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1, 2, 3],[4, 5, 6]]) # Create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [37]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7) # Create a constant array
print(c)

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)

e = np.random.random((2, 2))    # Create an array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.65322193 0.57651101]
 [0.34848656 0.95265952]]


Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [40]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1:3] # 1st 2 rows, index 1 to 3

print(a[0, 1]) # List 1, index 1 --> "2"

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
b[0,0] = 77    # b[0, 0] is the same piece of data as a[0, 1]

print(a[0, 1]) # "77"

2
77
